# Generated by Django 4.2.6 on 2023-11-21 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0005_tarjeta_solespe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
