# Generated by Django 4.2.6 on 2023-11-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0006_delete_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreSala', models.CharField(max_length=100)),
            ],
        ),
    ]
