# Generated by Django 4.2.1 on 2023-11-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0009_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensajeChat',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
